### ISSUE TITLE
[1.19.1] Эффекты работают сквозь блоки.

### ISSUE THREAD

**Issue by murao-kun** [dimadencep/Illuminations-forge#1]
Возможно это конфликт с чем-то, скорее всего с чем-то на оптимизацию. Использовал Rubidium, Starlight и Oculus.
![image](https://user-images.githubusercontent.com/110398598/182166610-ed7facec-fa64-459a-bdc3-dc2e5b65c035.png)

**Comment by dimadencep** [comment]
При тесте такой проблемы не было обнаружено

**Comment by murao-kun** [comment]
Спасибо. Апдейт сегодня?

**Comment by dimadencep** [comment]
извините, не увидел версию, фикс был для 1.16

на 1.19 баг еще актуален

**Comment by murao-kun** [comment]
Я заметил что такое случается только со starlight.
