### ISSUE TITLE
[1.18.2] Not all dashboard cosmetics are showing after fixing #12

### ISSUE THREAD

**Issue by V972** [dimadencep/Illuminations-forge#13]
I understand it's probably not a high priorty, but still.
I suspect the fix of #12 caused cosmetics other than head ones to not render (as only the overhead layer was added back if I understand correctly).

<img width="368" alt="image" src="https://user-images.githubusercontent.com/45125685/194352573-550e3d95-cd4a-4b3f-bc64-4c86f14b5736.png">

Despite me also having an aura and a wisp:
![image](https://user-images.githubusercontent.com/45125685/194352798-878046fd-2b1d-4c70-b0f0-aefbf2435839.png)

**Comment by dimadencep** [comment]
Tell me the uuid of your minecraft player

**Comment by V972** [comment]
55b1659a-810f-4687-a514-b3201b09fd69

**Comment by dimadencep** [comment]
![image](https://user-images.githubusercontent.com/66722732/194523309-3887f720-33a2-4aa1-8ef1-dd116c4410c4.png)

**Comment by dimadencep** [comment]
Are you sure you have the latest version of the mod?
Post your debug.log file

**Comment by V972** [comment]
Yes, I have the latest version - [1.18.2-1.10.2.18](https://www.curseforge.com/minecraft/mc-mods/illuminations-forge/files/4019028).

Debug log:
[debug.log](https://github.com/dimadencep/Illuminations-forge/files/9735277/debug.log)

I went into SP world first, then into MP server. Cosmetics work in SP, but not in MP 
([although the aura behaved weirdly with the rods "rotating into existance"](https://youtu.be/hA6yB7JYe4g). Perhaps due to my abysmal performace on this weak laptop).

![image](https://user-images.githubusercontent.com/45125685/194591103-d65a9ec0-2723-40bc-a5b1-c7b65a952065.png)
![image](https://user-images.githubusercontent.com/45125685/194593119-793a2444-7a6f-4549-b243-833c30ed970e.png)


Perhaps other optimizer(s) messing things up?
My pack (almost the same as in #11):

- Forge: 1.18.2 40.1.80

Oprimizers/renderers:

- flywheel-forge-1.18.2-0.6.5 (with `/flywheel backend off`)
- rubidium-0.5.3a
- RubidiumExtra-1.18.2-0.4.10.36
- milk_of_magnesium-1.18.2_v1.3.4
- canary-mc1.18.2-0.0.7 (fork of Lithium)

**Comment by dimadencep** [comment]
what server core are you using?

**Comment by V972** [comment]
Server owner said Vanilla server w/ Forge.

**Comment by dimadencep** [comment]
Now you also need to install this mod on the server
