### ISSUE TITLE
Forge Crash: Failed to Load Player Model 1.18.2 and Illuminations 3.0.0

### ISSUE THREAD

**Issue by viiizee** [dimadencep/Illuminations-forge#14]
This issue is still occurring on the latest version of the mod. I'm using Forge 1.18.2 - 40.1.73 with Illum Forge 3.0.0

I've tried with no mods installed and it works just fine; however, as soon as you place practically any other mod with this mod and the launcher crashes with this error.

[crash-2022-10-09_00.19.26-client.txt](https://github.com/dimadencep/Illuminations-forge/files/9741014/crash-2022-10-09_00.19.26-client.txt)

I would give you a list, but I'm telling you I sat here for nearly 2 hours testing individual mods with this mod and it happened nearly every time I loaded the client. I tested with probably 50+ popular mods and no Optifine, Shaders or anything else installed.

**Comment by dimadencep** [comment]
update mod
