### ISSUE TITLE
[1.16.5] Registry Object not present

### ISSUE THREAD

**Issue by antibang** [dimadencep/Illuminations-forge#4]
I've had this crash happen a few times, so I thought I'd report it :p

Seems to happen whenever I'm in a semi-dark or dark area

[crash-2022-08-06_07.30.17-client.txt](https://github.com/dimadencep/Illuminations-forge/files/9275026/crash-2022-08-06_07.30.17-client.txt)

**Comment by dimadencep** [comment]
You have an old version of the mod, please update. Why are you using the first version of the mod?

**Comment by antibang** [comment]
Sorry, I saw it had an update and had the intention to download it, but completely forgot :/ that's my mistake
