### ISSUE TITLE
[1.16.5]NullPointerException in When Dungeons Arise Structure "bandit_towers"

### ISSUE THREAD

**Issue by OcrSu** [dimadencep/Illuminations-forge#5]
NullPointerException in When Dungeons Arise Structure "bandit_towers"
Java11
Crashlog:https://bytebin.lucko.me/cEIpzrFy0t

**Comment by dimadencep** [comment]
can you describe the problem in more detail?

**Comment by OcrSu** [comment]
This is the crashlog provided by the players in my server. My server has deleted this mod. When I have free time, I will test this bug separately

> can you describe the problem in more detail?
